from app.routes import admin_routes
from app.routes import doctor_routes
from app.routes import user_routes
from app.routes import blood_bank_routes
from app.routes import lab_routes
from app.routes import hospital_routes
from app.routes import emergency_routes
from app.routes import ai_routes
from app.routes import job_application_routes
from app.routes import otp_routes
from app.routes import specialty_routes
from app.routes import location_routes
from app.routes import dean_routes
from app.routes import super_appointment_routes
