"""Minimal single-page PDF invoice generator (no external PDF dependency)."""
from __future__ import annotations


def _escape(text: str) -> str:
    return (
        str(text)
        .replace("\\", "\\\\")
        .replace("(", "\\(")
        .replace(")", "\\)")
    )


def build_pharmacy_invoice_pdf(
    *,
    order_public_id: str,
    pharmacy_name: str,
    status: str,
    currency: str,
    amount_total,
    lines: list[dict],
    patient_label: str = "Patient",
) -> bytes:
    """Return a simple PDF as bytes with order summary + line items."""
    y = 750
    content_lines: list[str] = []

    def text(x: int, yy: int, s: str, size: int = 11) -> None:
        content_lines.append(f"BT /F1 {size} Tf {x} {yy} Td ({_escape(s)}) Tj ET")

    text(50, y, "MEDCLUES Pharmacy Invoice", 16)
    y -= 28
    text(50, y, f"Order: {order_public_id}")
    y -= 16
    text(50, y, f"Pharmacy: {pharmacy_name}")
    y -= 16
    text(50, y, f"Status: {status}")
    y -= 16
    text(50, y, f"Patient: {patient_label}")
    y -= 24
    text(50, y, "Items", 13)
    y -= 18
    for item in lines[:30]:
        name = item.get("name") or "Item"
        qty = item.get("quantity")
        price = item.get("unit_price") or item.get("unitPrice")
        total = item.get("line_total") or item.get("lineTotal")
        piece = f"- {name}"
        if qty is not None:
            piece += f"  x{qty}"
        if price is not None:
            piece += f"  @ {currency} {price}"
        if total is not None:
            piece += f"  = {currency} {total}"
        text(50, y, piece[:110], 10)
        y -= 14
        if y < 80:
            break
    y -= 10
    text(50, y, f"Total: {currency} {amount_total if amount_total is not None else '—'}", 12)
    y -= 20
    text(50, y, "Generated by MEDCLUES. Partner invoice URL may also apply.", 9)

    stream = "\n".join(content_lines).encode("latin-1", errors="replace")
    objects: list[bytes] = []

    def obj(n: int, body: bytes) -> None:
        objects.append(f"{n} 0 obj\n".encode() + body + b"\nendobj\n")

    obj(1, b"<< /Type /Catalog /Pages 2 0 R >>")
    obj(2, b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
    obj(
        3,
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
    )
    obj(4, f"<< /Length {len(stream)} >>\nstream\n".encode() + stream + b"\nendstream")
    obj(5, b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")

    out = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for o in objects:
        offsets.append(len(out))
        out.extend(o)
    xref_pos = len(out)
    out.extend(f"xref\n0 {len(offsets)}\n".encode())
    out.extend(b"0000000000 65535 f \n")
    for off in offsets[1:]:
        out.extend(f"{off:010d} 00000 n \n".encode())
    out.extend(
        f"trailer\n<< /Size {len(offsets)} /Root 1 0 R >>\nstartxref\n{xref_pos}\n%%EOF\n".encode()
    )
    return bytes(out)
